version: '3'
services:
  postgres:
    image: postgres:15.2
    container_name: petclinic-postgres
    ports:
      - "5442:5432" # Host port 5442 maps to container port 5432
    environment:
      POSTGRES_DB: petclinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d petclinic"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0
    container_name: petclinic-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: patient_records
      MYSQL_USER: patient_user
      MYSQL_PASSWORD: patient_pass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./
    environment:
      OTEL_SERVICE_NAME: "PetClinic"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://host.docker.internal:5050"
      # Logs are disabled by default
      OTEL_LOGS_EXPORTER: "otlp"
      # Digma entries
      CODE_PACKAGE_PREFIXES: "org.springframework.samples.petclinic"
      DEPLOYMENT_ENV: "SAMPLE_ENV"
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petclinic
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9753/" ]
      interval: 20s
      timeout: 10s
      retries: 4
      start_period: 5s
    ports:
      - "9753:9753"
    entrypoint: java -jar -javaagent:/opentelemetry-javaagent.jar -Dotel.javaagent.extensions=/digma-otel-agent-extension.jar app.jar
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  tester:
    build: ./
    environment:
      OTEL_SERVICE_NAME: "PetClinicTester"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://host.docker.internal:5050"
      # Logs are disabled by default
      OTEL_LOGS_EXPORTER: "otlp"
      PETSHOP_URL: "http://app:9753"
      # Digma entries
      CODE_PACKAGE_PREFIXES: "org.springframework.samples.petclinic"
      DEPLOYMENT_ENV: "SAMPLE_ENV"
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petclinic
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    entrypoint: java -cp app.jar -Dloader.main=petclinic.client.ClientTester org.springframework.boot.loader.PropertiesLauncher
    depends_on:
      app:
        condition: service_healthy
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
  mysql_data:
