spring:
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /webjars/**
      static-locations:
        - classpath:/META-INF/resources/webjars/
        - classpath:/static/
        - classpath:/public/